<a href="https://colab.research.google.com/github/skyprince999/100-Days-Of-ML/blob/master/Basic_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

Constructing an empty array. No initialization is done

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.3677e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)  # Random initialization
print(x)

tensor([[0.2313, 0.7285, 0.4171],
        [0.6919, 0.8314, 0.1862],
        [0.7729, 0.3546, 0.8727],
        [0.8100, 0.4022, 0.1510],
        [0.0569, 0.3386, 0.2791]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)  # This is a matrix of dtype zeros
print(x) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # Constructing a tensor directly from data 
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2184,  1.2444, -0.2724],
        [ 0.9645, -0.8544,  0.9612],
        [-1.3630,  1.5570,  0.3942],
        [ 0.3678,  0.2142,  0.0065],
        [ 0.2083,  0.5133, -0.1978]])


In [8]:
print(x.size()) # get tensor size

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)    # Numerical operation

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [10]:
print(torch.add(x, y)) # similar operation

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [11]:
result = torch.empty(5, 3)   # you can provide an empty tensor as an argument
torch.add(x, y, out=result)
print(result)

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [13]:
# adds x to y (in place)
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[-1.6522,  2.9703, -0.4829],
        [ 2.1605, -1.4642,  2.4460],
        [-2.1954,  4.0052,  1.5117],
        [ 0.9436,  1.2360,  0.1958],
        [ 0.4780,  1.2232,  0.0746]])


In [14]:
# Standard Numpy indexing 
print(x[:, 1])

tensor([ 1.2444, -0.8544,  1.5570,  0.2142,  0.5133])


In [15]:
# Resizing is done via a view command

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3863])
-0.3862867057323456


In [17]:
# Converting torch tensor to numpy array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
# The memory allocation didn't change. Since it appears that both a & b point to the same memory location --> Not sure of this statement

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
b = b-1 
print(b)

[1. 1. 1. 1. 1.]


In [20]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [0]:
a = a+2

In [22]:
print(a)

tensor([4., 4., 4., 4., 4.])


In [23]:
print(b)

[1. 1. 1. 1. 1.]


In [24]:
# Converting from numpyarray to torch tensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

The autograd package provides for automatic differentiation of all Tensors. If a tensor is defined by `.requires_grads = True` 
it will track all operations on it. when you finish computation you can compute all gradients by calling `.backward()`

These gradients are then stored in `.grad` attribute 



In [26]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [27]:
# Computing a tensor operation 
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
print(y.grad_fn) # since y was created from an operation it has a grad_fn

In [30]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [35]:
#.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

a = torch.randn(2, 2)
b = ((a * 3) / (a - 1))
print(a.requires_grad)
print(b)
print(b.grad_fn)

False
tensor([[0.3416, 1.9399],
        [1.8257, 2.0705]])
None


In [36]:
# you can set the flag to True
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

True
tensor(10.7434, grad_fn=<SumBackward0>)


In [0]:
x = torch.ones(2, 2, requires_grad=True)

y = x + 2

z = y * y * 3
out = z.mean()

out.backward() # by this we do a  backward propogation 

In [39]:
print(x.grad) # This prints out the gradients  d(out)/dx
              # Does thsi becomes an engine for computing vector-JAcobian product

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [40]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 546.5828, -564.4034, -702.7866], grad_fn=<MulBackward0>)


In [41]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 870.7783, 1161.6377, -543.9890], grad_fn=<MulBackward0>)


As a note if you do a `.detach` you can remove it from the computational history and stop further operation tracking from taking place

To prevent tracking & save memory, the entire code block can be run with the following code wrapped: `with torch.no_grad()`

In [42]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [43]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [44]:
# understanding the tensor operation
x.eq(y)

tensor([True, True, True])

In [47]:
print(x)
print(y)

tensor([ 0.8504,  1.1344, -0.5312], requires_grad=True)
tensor([ 0.8504,  1.1344, -0.5312])


In [46]:
y

tensor([ 0.8504,  1.1344, -0.5312])