<a href="https://colab.research.google.com/github/skyprince999/100-Days-Of-ML/blob/master/Basic_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

Constructing an empty array. No initialization is done

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.3677e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)  # Random initialization
print(x)

tensor([[0.2313, 0.7285, 0.4171],
        [0.6919, 0.8314, 0.1862],
        [0.7729, 0.3546, 0.8727],
        [0.8100, 0.4022, 0.1510],
        [0.0569, 0.3386, 0.2791]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)  # This is a matrix of dtype zeros
print(x) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # Constructing a tensor directly from data 
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2184,  1.2444, -0.2724],
        [ 0.9645, -0.8544,  0.9612],
        [-1.3630,  1.5570,  0.3942],
        [ 0.3678,  0.2142,  0.0065],
        [ 0.2083,  0.5133, -0.1978]])


In [8]:
print(x.size()) # get tensor size

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)    # Numerical operation

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [10]:
print(torch.add(x, y)) # similar operation

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [11]:
result = torch.empty(5, 3)   # you can provide an empty tensor as an argument
torch.add(x, y, out=result)
print(result)

tensor([[-0.4338,  1.7259, -0.2105],
        [ 1.1960, -0.6099,  1.4848],
        [-0.8325,  2.4481,  1.1175],
        [ 0.5759,  1.0218,  0.1893],
        [ 0.2696,  0.7099,  0.2724]])


In [13]:
# adds x to y (in place)
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[-1.6522,  2.9703, -0.4829],
        [ 2.1605, -1.4642,  2.4460],
        [-2.1954,  4.0052,  1.5117],
        [ 0.9436,  1.2360,  0.1958],
        [ 0.4780,  1.2232,  0.0746]])
